### ISSUE TITLE
US_07 // Filter

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#13]
## Value Proposition
As a `user`
I want to `filter events` 
In order to `find the events I’m interested in`

## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/dee50e2a-9ce1-4bc1-aa9d-64eab9cb6742)

## Acceptance Criteria
- [ ] In EventList component add two filter bars are shown: one for categories and the other for other properties
- [ ] clicking on a filter updates the list of events to only show corresponding events and hides events, which do not match the selected filter criteria

## Tasks

- [ ] further research mongoose filter() functionality
- [ ] Updated backend (GET) to accept filter as query
- [ ] create `FilterBar` component
- [ ] Define filters for categories and City
- [ ] implement `FilterBars` in EventList
- [ ] connect mongoose filters and `FilterBar`

**Comment by julialoeschel** [comment]
nice!
just little things: 
- in AC you dont need to name the Component. Rememeber, this is for non-developers. let everybody understand the aim. 
`at the top of the Homepage there are two filter bars: one for categories and the other for other properties`
- what happens if the filter doesnt show any results? (a second sreibble is always helpful for that)

**Comment by NikRoe** [comment]
LGTM
