### ISSUE TITLE
US_08 // Search Events

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#14]
## Value Proposition
As a `user
I want to `search events` 
In order to `find specific events’

## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/f6923118-b9a9-4860-b0d8-5222ee0353e0)

## Acceptance Criteria
- [ ] a search bar is at the top of the MainPage
- [ ] The search bar should have a placeholder text that says “Search...” to provide a hint to users about its functionality.
- [ ] after entering a search query the results are shown on the page

## Tasks
- [ ] Create a search bar component that renders an input field 
- [ ] Add the search bar above the filter bars in the Main Page
- [ ] Implement the placeholder text “Search...” within the search bar.
- [ ] under pages create a new search.js file
- [ ] after submitting the search query, redirect to the new serach page

**Comment by julialoeschel** [comment]
great!

I have some thoughts on this:
- do all the filters relay on anything?  (do I have to type, or to choose from any other filters? )
-  what does happen if there is no search result? 
- do we really need a new page with results, or shall we just display the results on the homepage?
- will you search in headlines or in all texts of the event? (my advice: start with headline ;) )

**Comment by fel-sad** [comment]
Hi @julialoeschel , thank you for the feedback! We plan to update the user story accordingly:

1. We'll update accordingly to also show a message in case their are no matching events.
2. We want to implement the search results on a new page to control the interoperability between filters and search:
- filter currently will affect the displayed events on the MainPage
- in the next UserStory(US_09) the default state of the MainPage will also show highlighted events, as well as filtered events should they be applied.
To avoid too many states on the MainPage and enable us to adapt the search in different scopes ( category only, app-wide for all events) we think this approach provides us more flexibility and adaptability. 
What do you think?

3.  Currently we plan to only search the event titles. We'll add an extension for descriptions to the add-on list, but would want to prototype it first.

**Comment by julialoeschel** [comment]
Hey, 
1. great
2. I am still not convinced but Iam ready to be proven wrong on this. Iam excited to see what you develop here. 
3. great, that a good idear. The extended seacrch could be a small extra userstorry any time later.
