### ISSUE TITLE
#US_09 // Category Pages

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#15]
## Value Proposition
As a `user` 
Im want to explore `specific event categories`, 
I order to `explore categories to discover new events`.

## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/99dce343-7734-47bc-b31d-dec001893581)

## Acceptance Criteria
- [ ] On the Main Page, there should be a section displaying different categories with highlighted events.
- [ ] Each category highlights only 2-3 events and has a Link to navigate to the CategoryPage for that category.
- [ ] On the CategoryPage is a picture and the Category name as title and a back button, that redirects to the MainPage
- [ ] On the CategoryPage is a list of all events in the category.         
 
## Tasks
- [ ] Create a `CategoryHighlight` Component, that displays the category and only 2-3 events per category as well as a link to the category page via dynamic routing.
- [ ] Implement `CategoryHighlight` on the MainPage replacing `EventList`
- [ ] create dynamic routing for category pages including:
  - [ ] Image, conditionally rendered based on category
  - [ ] Title
  - [ ] Back Button
  - [ ] EventList filtered according to current category

**Comment by julialoeschel** [comment]
great job!
🦆
