### ISSUE TITLE
US_10 // Multi-Step Create Form

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#17]
## Value Proposition
As a `user`
I want to `easily create events` 
without `dealing with a long form`
## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/c127b59d-7986-4380-b706-f1f9165a859e)

## Acceptance Criteria
- [x] When creating a new event users are guided through the process by a form with multiple steps instead of one big form
- [x] The creation process structure is similar to implemented field sets: event basics, additional infos like categories and finally event details
- [x] event data is saved while going back and forth in the multistep form but only submitted after users click submit in the end
- [x] users can preview the pre-filled form and edit it if needed before they submit it.
- [x] data is not saved when users leave the form without completing it or submitting the event data.
- [x] while navigating through the form, a progressbar shows the current stept to the user.

## Tasks
- [x] create state, to only show one fieldset at a time to users
- [x] implement a progress bar according to the current (number of) fieldsets
- [x] render “next” and “back” button to move between fieldsets and submit button only on the last fieldsets
- [x] add data validation on submit-
- [x] design confirmation screen for users to review their data before final submission.

**Comment by julialoeschel** [comment]
Hello there. 
good one! 
I have some thoughts on this: 
- there is no mentioning of the Progress bar in the AC. This would be nice to know. 
- the heading TASKS is double.
- the scribble shall also include the information screen. 
- is the data saved if you move back ? (not leaving the form)

good job Team 🦆

**Comment by alhen002** [comment]
Hello @julialoeschel ,

we already made the requested changes. Concerning the scribble - it's already in there. last image. 
See also ` event data is saved while going back and forth in the multistep form but only submitted after users click submit in the end` concerning your question concerning if data is saved. 

all the best

Alex

**Comment by abaibik** [comment]
Hey-hey,
LGTM 👍
Could you only make the Acceptance Criteria shorter? For example, "When creating a new event users are guided through the process by a form with multiple steps" (without explanation)
