### ISSUE TITLE
US_11 // Location Autocomplete

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#18]
## Value Proposition
As a ‘user’ 
I want to `easily and accurately fill in location data`
so that events are `easy to find for users in real life`

## Description
- Scribble / design or text- Precise, no unnecessary information

## Acceptance Criteria
- [ ] In the multi-step-form replace the city and location input with mapbox autocomplete.
- [ ] When the input fields are empty there should be no suggestions displayed. 
- [ ] when users enters an address or location mapbox supplies suggestions and fills out remaining fields if users pick a suggested location
- [ ] in addition to the location inputs a preview map is shown to allow users to quickly check if the suggested location is correct

## Tasks
- [ ] setup mapbox api and install mapbox
- [ ] integrate mapbox autocomplete in multi-step-form and update input fields
- [ ] update DB event model to accept mapbox response

**Comment by TheRealChio** [comment]
looks great! one thing that would be good to know is if the user can also interact with the map if he/she is not happy with the location? :)

**Comment by alhen002** [comment]
Hello @TheRealChio, 
at first no. we'll implement this in a future US.

Ready for your green hook, if you are.
