### ISSUE TITLE
US_12 // Mapbox DB Implementation

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#19]
## Value proposition
As a `user` 
I want to `accurate location data` 
In order to `easily find events in real life`
## Acceptance criteria
- [ ] In the Preview List of Events: display city according to Mapbox data
- [ ] On the EventDetails Page: display location according to Mapbox data
- [ ] On the EventDetails Page: a map of the event location is visible on the details page

## Tasks
- [ ] update DB event model and replace City and location fully with mapbox response
- [ ] cleanup db
- [ ] update EventList to use data supplied by mapbox
- [ ] update EventDetails to use data supplied by mapbox
- [ ] add a map view of the location to EventDetails

**Comment by julialoeschel** [comment]
great job!

I have just a little trouble understanding the first 2 points of AC. 
`In the Preview List of Events: display city according to Mapbox data` -  as text or image, and could you scribble that view as well? 
` On the EventDetails Page: display location according to Mapbox data` - I am assuming you mean text, but where exactly? 

one remark here: sometimes the cities you get from mapbox are loooooooooooooong, maybe you want to prevent messing up your layout.

im excited to see how you implement this!
great job.

**Comment by alhen002** [comment]
Hey @julialoeschel ,
we updated our acceptance criteria. To be honest, they were a bit missleading as they were just describing the new data flow. For the user in the frontend, nothing will change, except the visibility of the map.
