### ISSUE TITLE
US_14 // USER DB & ownedEvents

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#26]
## Value proposition
As an `user`,
I want to `manage events only created by me and see them on one place`  
In order to `not affect other users events`
## Description
![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/cc342567-b789-4e74-acc4-c587d79e8b95)
## Acceptance criteria
- [ ] in the burger menu a new Link is added, which redirects to the owned Events Page
- [ ] when visiting the site, the events of the users are fetched and displayed
- [ ] if no events were found a message is displayed
- [ ] if an error occurred an error message is displayed
## Tasks
- [ ] edit the Events Schema to connect to the User Schema
- [ ] create a new Page `events/ownedEvents.js`
- [ ] fetch the associated events and render them on the `ownedEvents` page within the `<EventList />` Component
- [ ] add a new Link inside of the BurgerMenu Component

**Comment by julialoeschel** [comment]
amazing. 🐜
