### ISSUE TITLE
US_13 // Next Auth

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#27]
## Value Proposition
As a `user`
I want to `log in` 
In order to `create my events`

## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/8a13ca92-78b8-4c6a-9eaf-40104193f429)

## Acceptance Criteria
- [ ] In the burger menu a Login Button added, which links to the LoginPage. Once logged-in the button displays log out.
- [ ] On the LoginPage users can use their github account to login
- [ ] once successfully logged in users are redirected to the main page
- [ ] once logged in the profile picture and a greeting message is shown

## Tasks
- [ ] install next Auth
- [ ] configure next Auth with github as provider
- [ ] add user collection to db and create appropriate schema
- [ ] Implement Login LinkButton in burger menu, that conditionally renders logout if the the user is logged-in
- [ ] Create LoginPage and Login Component
- [ ] conditionally render profile picture and greeting if logged in

**Comment by julialoeschel** [comment]
great work!
