### ISSUE TITLE
US_15 // Create Form with User

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#28]
## Value proposition
As a `user`
I want to `create an new event associated to me` 
In order to `keep track of my events and secure them`
## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/c7beae4b-8fb1-4827-8d3e-a71ded5477be)

## Acceptance criteria
- [x] in the burger menu a, clicking on the “create” link will redirect to the create page
- [x] in the form there is no organizer input any more
- [x] on the detail page of an event the organizer is a valid user and is displayed
## Tasks
- [x] Go to the `create.js` and delete the Organizer input in the form
- [x] Get the User-Information from next-auth
- [x] edit the `handleSubmit’ function the send the user data in addition
- [x]  protect the backend route `pages/api/events` - so only logged in users can create an event
- [x] create specific error handling for this
- [x] in the ‘EventDetail’ Component edit the organizer field and replace it with the actual user, in the db.

**Comment by julialoeschel** [comment]
great job! 
One thing comes into my mind: is the app any usable, if there is nobody logged in? Here it seems like the "stranger" (not logged in User) can work on the form until its sent. Is there any mechanism to prevent this? 
- this could be an extra US, as well as be part of this.

**Comment by julialoeschel** [comment]
oh ok. great. 
your good :)
