### ISSUE TITLE
US_17 // Logged-in Edit

### ISSUE THREAD

**Issue by rythinks** [alhen002/capstone-event-repo#29]
## Value Proposition
As a `logged-in user`
I want to `edit` an event 
so only `I can edit my events` overview.

##Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/fb30de22-6c71-4862-8173-878a7ed5b97e)

## Acceptance Criteria
- [x] only I, as the owner of an event, can edit the event
- [x] when not logged in, the edit button is not shown

## Tasks
- [x] implement the functionality to check, if the logged-in user is the owner of the event before editing
- [x] conditionally render the edit button only, when the logged-in users is the owner of the event
- [x] protect the backend route pages/api/events - so only logged in users can create an event
- [x] create specific error handling for this

**Comment by julialoeschel** [comment]
great job!
