### ISSUE TITLE
US_16// User Story

### ISSUE THREAD

**Issue by MukaddesUzdoganlar** [alhen002/capstone-event-repo#30]
## Value proposition
As a `logged-in user`
I want to `delete` 
In order to `get a cleaned overview`
##   Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/141938486/6937aaa7-c4cf-4539-ace9-8b6561a71988)

## Acceptance criteria
- [ ] In the BurgerMenu a new Link is added, which redirects to the owned Events Page. 
- [ ] The logged-in users get a request to delete an event, the system should allow the deletion.
- [ ] After successfully deleting an event the event should be removed from the owner’s schedule and the user get a confirm message. 
## Tasks
- [ ] Implement the functionality to check if the logged-in user is the owner of the event before deletion.
- [ ]  Protect the backend route pages/api/events - so only logged in users can create an event
- [ ] Show the event owner a confirm message that the event is removed from the owner List. 
- [ ] Hide the delete functionality for guest users.

**Comment by julialoeschel** [comment]
hey there. great job. 
just one thing, your VP is a little confusing for me :) 
`As a logged-in user
I want to delete`  what? everything? ;) 

the rest of the US is great, just specify the VP a little and you are good to go!
