### ISSUE TITLE
US_18 // Frontend Route Protection

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#31]
## Value proposition
As a `logged-in user`
I want `other users to stay off my events`
so only `i am able to edit, delete or create events`
## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/768d7e95-b4f8-4dcc-bc03-1b3166ee2026)

## Acceptance criteria
- [ ] when the user is logged in, in the Burger Menu the `create, ownedEvents, logout, home` links are shown
- [ ] as a non-logged in user, in the Burger Menu `login, home` links are shown
- [ ] when a user is navigating to the create, ownedEvents and is not logged in the user will be redirected to the login page & can’t access the pages
## Tasks
- [ ] when the user is logged in, in the Burger Menu the `create, ownedEvents, logout, home` links are shown
- [ ] as a non-logged in user, in the Burger Menu `login, home` links are shown
- [ ] when a user is navigating to the create, ownedEvents and is not logged in the user will be redirected to the login page & can’t access the pages

**Comment by FelineHuhn** [comment]
Nice user story :) I think the value proposition is a bit misleadingly expressed, since you don't want to "stay off" anyone from an event. Maybe you could change it to something like 

**I want to** have exclusive control over the events I create,
**in order** to preventing unauthorized editing, deletion, or creation by others.

or what do you think? :) 

In general, the acceptance criteria could be a bit less technical (e.g. instead of `create`, `ownedEvents`, `logout`, `home` links you should mention it more descriptive or with the exact text content of the links...) but that's ok for my for now, you can pay attention to it again a bit more in upcoming user stories. 

I think you you forgot to write your tasks, since the tasks are copy pasted from the acceptance criteria!? :D 

Tasks could be written something like: 

- [ ] Implement the navigation menu to display the appropriate links based on the user's login status
- [ ] Configure the redirection behavior for unauthorized users attempting to access restricted pages
- [ ] Ensure that only the event creator can edit or delete their events, and handle unauthorized attempts with clear error messaging

**Comment by FelineHuhn** [comment]
LGTM now :)
