### ISSUE TITLE
US_23 // Toast Notifications

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#32]
## Value proposition
As a `user`
I want to `get confirm notifications`
In order to `get feedback for my actions`
## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/8aa0f280-c09f-40ff-8a3e-5a1e73fd5170)

## Acceptance criteria
- [ ] after creating, editing or deleting an event a confirm message with the corresponding action will be shown on the top of the screen
## Tasks
- [ ] install the library react-hot-toast
- [ ] in _app.js import Toaster from react-hot-toast
- [ ] place the imported Toaster component inside the SWRConfig next to GlobalStyles
- [ ] inside all the handler functions for create, edit and delete execute the function toast.success(“New project created”) below the the mutate() function

**Comment by FelineHuhn** [comment]
Nice user story 🙌

Just one tiny thing: Your acceptance criteria could be a bit more detailed. You could add two more points in my opinion: 
 

- [ ] The confirmation message should clearly indicate the action that was performed (e.g., "Event created," "Event edited," "Event deleted")
- [ ] The confirmation message should automatically disappear after a few seconds to avoid obstructing the user's view.

**Comment by FelineHuhn** [comment]
Super 🚀
