### ISSUE TITLE
US_19 // Attending Events

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#33]
## Value proposition
As a `logged-in user`
I want to `mark the Events I participate in`
In order to have `an overview of all the Events I want to go to`

## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/7325514e-f0cb-4310-b1ea-451245a46a25)

## Acceptance criteria
- [ ] On the EventCard and the Event DetailPage I can toggle an participate bookmark.
- [ ] In the Burgermenu I can find a Link to a page with all the events I want to go to
- [ ] On the DetailPage of an event I can see which other users plan to attend
## Tasks
- [ ] Go to the EventCard and DetailPage component and add a bookmark icon
- [ ] Write a handle bookmark function, which saves the bookmarked events to users
- [ ] import the handle bookmark function to EventCard and DetailPage 
- [ ] Create a Bookmarked event page where you fetch all your bookmarked events

**Comment by fel-sad** [comment]
@FelineHuhn Thank you for the suggestions! We just updated the user story. 🙌

**Comment by FelineHuhn** [comment]
LGTM now 🚀
