### ISSUE TITLE
US_22 // Light/Dark Mode

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#34]
## Value proposition
As a `user`
I want to `customize` the theme of the app
In order to it `looks` better to me
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] Two button’s are displayed in the BurgerMenu, one for the dark mode and one for the light mode
- [ ] Clicking one of the buttons will activate the selected theme and apply the styling on the application
## Tasks
- [ ] Install next-themes
- [ ] In _app.js import Theme Provider from next-themes
- [ ] Place the imported Theme Provider component inside App function
- [ ] Import useTheme in Projects Overview Page and implement to set theme
- [ ] Create two Button’s for dark and light mode in Buttons.js and import it in Projects Overview Page
- [ ] Implement onChange function to set theme

**Comment by julialoeschel** [comment]
great job!
