### ISSUE TITLE
US_25 // Custom 404 Page

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#45]
## Value proposition
As a `user`
I want to `get to a separate 404 Page` 
In order to `have a branded error page`
## Description
![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/ce006052-eb3b-4743-b647-72d4ec0a1919)
## Acceptance criteria
- [ ] when the user is directing to a page that is not existing, a custom error page is shown
- [ ] A Back to Home Button is displayed
- [ ] Clicking on the Button will redirect the user back to the Main Page 
## Tasks
- [ ] Go to Pages and create a 404 Page
- [ ] Create a Back to Home Button, which will redirect to the Home Page

**Comment by julialoeschel** [comment]
great Story.

make sure you follow the[ next.js 404 handling](https://nextjs.org/docs/pages/building-your-application/routing/custom-error#404-page).
