### ISSUE TITLE
US_27 // Image Upload

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#46]
##Value Proposition
As a `logged-in user`
I want to `upload my own images for events I create` 
In order to `show users what they can expect from the event`

##Description

##Acceptance Criteria
- [ ] When creating or updating an event users can upload their own images instead of linking an image from unsplash.

##Tasks
- [ ] install and connect cloudinary
- [ ] replace input for the image link with cloudinary upload in events/create
- [ ] add the image upload to the DetailPage in edit mode

**Comment by FelineHuhn** [comment]
Great feature 🚀
