### ISSUE TITLE
US_26 // Category Overview Page

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#47]
## Value proposition
As a `user`
I want to `have an overview of all available categories`
In order to `choose the right category suited for my interests`
## Description

![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/7358de0f-6ed5-4ac0-9ed1-9935312f35f5)

## Acceptance criteria
- [ ] in the menu a categories Link is added
- [ ] after clicking the link, the user will be redirect to the categories page
- [ ] selecting a category, on the page, will redirect the user to the specific category detail page
## Tasks
- [ ] add a categories/index.js file
- [ ] fetch all the categories with SWR
- [ ] create a `Category Component`, which will render the picture of the category and a Link, that will redirect to the specific category
- [ ] render the category component for each category of the fetched categories
- [ ] style the category component using styled compo

**Comment by FelineHuhn** [comment]
The overview page is a great feature! 🫶 Some thoughts from me: 

The wireframe is somehow not meaningful enough for me. The wireframe is somehow not meaningful enough for me. Shouldn't there be different small images shown? Maybe it would be useful to visualize where the user comes from before (the menu which is mentioned in the acceptance criteria) and where he goes to when he clicks on one of the images (specific category detail page which is also mentioned below)?

The underlined "city" in the wireframe confuses me. When there should be a real city name, I would like to show it in the wireframe already. Also when this is a back link you should mention the back link in you acceptance criteria and tasks.

**Comment by alhen002** [comment]
@FelineHuhn ,

all clear, updated the WF.

**Comment by FelineHuhn** [comment]
AWESOME
