### ISSUE TITLE
US_24// Pop Up Modal

### ISSUE THREAD

**Issue by MukaddesUzdoganlar** [alhen002/capstone-event-repo#48]
## Value proposition
As a `user`
I want to have a confirmation `pop-up window` 
In order to confirm or verify the `action`
## Description
![Image](https://github.com/alhen002/capstone-event-repo/assets/141938486/78c74862-2cda-4345-bf91-81c359e0926e)
## Acceptance criteria
- [ ] User’s get a confirmation pop-up window when the user attempts to delete an event. 
- [ ] The pop-up should display a message that clearly describes the action to be confirmed.
- [ ] The pop-up should have "Confirm" and "Cancel" buttons for the user to make a choice.
- [ ] When the "Cancel" button is clicked, the action should be canceled, and the pop-up should close.
## Tasks
- [ ] Install the library for pop-up
- [ ] Implement the functionality to display the pop-up.
- [ ] Add "Confirm" and "Cancel" buttons and ensure they trigger the appropriate actions.
- [ ] Implement the option to close the pop-up without confirming the action.

**Comment by FelineHuhn** [comment]
Very clear user story 🙌 
Only one acceptance criteria to add: You should mention also, what happens when the "Confirm" button is clicked (the corresponding event is deleted and the user redirects to...). The logic behind that should be also mentioned in the task ("add the previous delete logic to the "Confirm" button" or something like that).
