### ISSUE TITLE
US_28 // Animations

### ISSUE THREAD

**Issue by robinschubertdev** [alhen002/capstone-event-repo#49]
US_28 // Animations

##Value Proposition
As a `user`
I want to `see nice animations` 
In order to `get entertained and get interest in exploring the app`

##Description
- Scribble / design or text- Precise, no unnecessary information

##Acceptance Criteria
- [ ] when the unser clicks on the burgermenu it expands with an animation
- [ ] when the user clicks on the attend button a small
- [ ] when clicking on the search button an animation will be executed

##Tasks
- [ ] install an animations library 
- [ ] impliment animations for all nescessary components

**Comment by FelineHuhn** [comment]
Nice idea for better user experience! 🙌

You description sounds like the default template, or? Please adjust this part with y short description, when you don't have wireframes for that user story. 

The second acceptance criteria is just a Spoiler "a small.........." - I want to know what happens than 😁

You task with "all necessary components" is perhaps a bit too inaccurate, isn't it? Perhaps briefly mention all the relevant components?

Also I asked me if it would be cool to implement also a loading animation, when the events data are loading. What do you think?

**Comment by robinschubertdev** [comment]
we will add a loading animtion in our styled components user story

**Comment by FelineHuhn** [comment]
Significant improvement! 🙌
