### ISSUE TITLE
#US_04/Delete an Event - Detail Page

### ISSUE THREAD

**Issue by fel-sad** [alhen002/capstone-event-repo#5]
##Value Proposition
As a `user`,
I want to `delete an event that I shared`
In order to `keep the list of local events up to date`

![Image](https://github.com/alhen002/capstone-event-repo/assets/142178179/e729c17c-ba52-4619-9f14-faf0e5f704a7)

##Acceptance Criteria
- [ ] A Delete Button is added at the bottom of the DetailsPage
- [ ] Clicking on the delete button, will delete the event and redirect to the MainPage

##Tasks
###Backend
- [ ] in /pages/api/events/[id].js :  create a new DELETE Method, accept the id through the request.query
- [ ] use the Mongoose Method findIdAndDelete to Delete the Event
- [ ] implement error handling with try / catch
###DetailPage
- [ ] create an async handleDelete function that fetches to the url api/events/${id}, method type: “DELETE”
- [ ] implement error handling with try/catch
- [ ] if response.ok redirect to MainPage with router.push(“/”)
- [ ] create a Button and add an onClick event, invoke the newly created function handleDelete

**Comment by FelineHuhn** [comment]
Hey ducks, what about a delete modal which opens, when clicking the delete button, which asks the user, if the event really should be deleted? Could improve the user experience a lot, or? Or did you plan that for a later user story?

**Comment by alhen002** [comment]
Hey Fleine, thank you for your comment. We thought about building our own custom modal for the future. But you're right, for the moment, we'll go with an [confirm() ](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm?retiredLocale=de)method, we'll add this to the story :)
