### ISSUE TITLE
US_5 // Edit an Event

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#6]
## Value proposition
As a `user`,
I want to `edit an event that I shared`
In order to `keep planned events up to date`
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] An Edit Button is added to the DetailsPage
- [ ] Once clicked additional Cancel and Save buttons appear and users can simple edit the fields in the layout of the edit page and update values
- [ ] updates are saved once users click save, or discarded with a click on Cancel
## Tasks
- [ ] create a new useState: editMode (true, false)
- [ ] create an handleEdit function that sets editMode to true and sets current event information as default values in a new form.
- [ ] create an async handleSave function that fetches to the url api/events/${id}, method type: “PUT”, headers snippet and sends the updated data in the body 
- [ ] create an edit Button and add an onClick event, invoke the newly created function handleEdit function.
- [ ] create an save Button and add an onClick event, invoke the newly created function handleSave function.
- [ ] create an cancel Button as Styled Link that sets the edit mode to false without updating the data

**Comment by shrocket** [comment]
Thank you again for letting me look at your User Story! Here are my thoughts:
- super fantastic value proposition!
- in the acceptance criteria:
  - should the fields perhaps be labeled? I can imagine a scenario where I have deleted the contents of a field and then cannot remember what kind of content should go in there.
  - what happens if the user has made changes, and then clicks `back` instead of `save` or `cancel`?
- also a super fantastic task list!

Keep up the good work and happy coding!

**Comment by julialoeschel** [comment]
great story 🦆 , 
nothing to add here. 

keep up the good work.
