### ISSUE TITLE
US_06 // Navigation

### ISSUE THREAD

**Issue by alhen002** [alhen002/capstone-event-repo#7]
## Value proposition
As a `user`,
I want to `navigate on the page easily`
In order to `access all the pages in one single place`
## Description
![Image](https://github.com/alhen002/capstone-event-repo/assets/106553644/ec562ad0-66ca-41d7-aa4e-c2e7cf32c4e5)
## Acceptance criteria
- [ ] In the `Header` the user can navigate through the different pages of the application
- [ ] to access the menu a burger menu is shown - when the user clicks on it the menu will open and a second click on the burger menu will close it again
- [ ] in the menu the user can click create to get to the form to create new events
- [ ] in the menu the user can click home to get back to the MainPage
## Tasks
- [ ] create a `Layout` component, that wraps around the other elements to ensure the the menu is shown on all pages
- [ ] create the `Menu` Component and burger menu button with minimal styling via styled components
- [ ] implement the `Menu` Component in t he `Header` Component
- [ ] implement the `Header` Component in the `Layout` Component
- [ ] write a handleMenu function to show / hide the menu onClick

**Comment by julialoeschel** [comment]
Hey, great job. 
one little thing comes to my mind: do you want to indicate at which page the user is , or disable the HOME button, when already on Homepage? 

if so: this could also be a small extra userstory for the future. ;) 

also I found one typo 
implement the Menu Component in **t he** Header Component


good story 🦆 !
